# Generated by Django 5.2.17 on 2026-09-17 02:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., 10 Min Meditation, No Sugar', max_length=150)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=10)),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('is_completed_today', models.BooleanField(default=False)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mood', models.CharField(choices=[('GREAT', '😄 Great'), ('GOOD', '🙂 Good'), ('CALM', '😌 Calm'), ('ANXIOUS', '😰 Anxious'), ('TIRED', '😴 Tired'), ('SAD', '😔 Sad')], default='GOOD', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('exercise_type', models.CharField(help_text='e.g. Morning Jog, Yoga, Cycling', max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('intensity', models.CharField(choices=[('LOW', 'Low (Walking, Yoga)'), ('MODERATE', 'Moderate (Jogging, Cycling)'), ('HIGH', 'High (HIIT, Running, Gym)')], default='MODERATE', max_length=10)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bedtime', models.TimeField(help_text='Time went to bed')),
                ('wake_time', models.TimeField(help_text='Time woke up')),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Total sleep duration in hours', max_digits=4)),
                ('quality_rating', models.IntegerField(default=4, help_text='Rating 1 to 5 stars')),
                ('disturbances', models.TextField(blank=True, help_text='Notes on wakeups or disturbances', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('glasses_logged', models.PositiveIntegerField(default=0, help_text='Number of 250ml glasses logged')),
                ('goal_glasses', models.PositiveIntegerField(default=8, help_text='Daily goal in glasses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
